// <auto-generated />
namespace XmsExam.Migrations.ApplicationUsersMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class testuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testuser));
        
        string IMigrationMetadata.Id
        {
            get { return "201808161606433_test user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
